service: serverless-survey-forms-cdn

provider:
  name: aws
  runtime: nodejs8.10
  description: "The AWS CloudFormation template for this Serverless application's resources to unify endpoints of S3 and APIGW"
  region: ${env:REGION}
  
custom:
    stage: ${opt:stage, 'dev'}
    project: serverless-survey-forms
    region: ${env:REGION}
    apigwid: ${env:APIGWID}

resources:
  Resources:
    WebsiteCDN:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Comment: 
            Fn::Join:
            - ''
            - - 'Cloudfront Distribution pointing to '
              - "${self:custom.project}"
              - "-"
              - "${self:custom.stage}"
          Enabled: true
          Origins: 
            - DomainName:
                Fn::Join:
                - ''
                - - "${self:custom.project}"
                  - "-"
                  - "${self:custom.stage}"
                  - "-webclient.s3.amazonaws.com"
              Id: WebClientS3
              CustomOriginConfig:
                HTTPPort: '80'
                HTTPSPort: '443'
                OriginProtocolPolicy: http-only
            - DomainName:
                Fn::Join:
                - ''
                - - "${self:custom.apigwid}"
                  - ".execute-api."
                  - "${self:custom.region}"
                  - ".amazonaws.com"
              Id: APIGW
              OriginPath:
                Fn::Join:
                - ''
                - - "/"
                  - "${self:custom.stage}"
              CustomOriginConfig:
                HTTPPort: '80'
                HTTPSPort: '443'
                OriginProtocolPolicy: match-viewer
          CacheBehaviors: 
            - PathPattern: api/*
              AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
              Compress: 'true'
              TargetOriginId: APIGW
              ForwardedValues:
                Headers:
                - Authorization
                - If-Modified-Since
                QueryString: 'true'
              ViewerProtocolPolicy: redirect-to-https
            - PathPattern: authentication/*
              AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
              Compress: 'true'
              TargetOriginId: APIGW
              ForwardedValues:
                Headers:
                - If-Modified-Since
                QueryString: 'true'
              ViewerProtocolPolicy: redirect-to-https
          DefaultCacheBehavior:
            Compress: true
            DefaultTTL: 3600
            TargetOriginId: WebClientS3
            ForwardedValues: {
                "Headers": ["If-Modified-Since"],
                "QueryString": "true"
              }
            ViewerProtocolPolicy: allow-all
          DefaultRootObject: index.html
